import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header/Header";
import { Toaster } from "sonner";
import SessionProvider from "@/components/auth/SessionProvider";
import SessionReloader from "@/components/auth/SessionReloader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kr">
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <SessionProvider>
          <SessionReloader>
          <Header />
            <div className="children">
              {children}
            </div>
            </SessionReloader>
          </SessionProvider>
        <Toaster richColors />
      </body>
    </html>
  );
}
